### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by gustavosotnas** [gustavosotnas/SysRadoc-Prototipo-GUI-INF-UFG#1]
Pastas do protótipo: 

#### Telas sem login

- [x] Página inicial SysRadoc - D
- [x] Cadastro SysRadoc - D
- [x] Sucesso_Cadastro SysRadoc - D
- [x] Recuperação_Cadastro SysRadoc - D
- [x] Sucesso_Recuperação_Cadastro SysRadoc - D

#### Telas com login

- [x] Home_Wizard SysRadoc - D
- [x] Passo1_EnviarRadoc_Wizard SysRadoc - D
- [x] Passo2_SucessoEnvioRadoc_Wizard SysRadoc - D
- [x] Passo2.1_FalhaEnvioRadoc_Wizard SyRadoc - D
- [x] Passo3_Processando_AvaliaçãoRadoc_Wizard SysRadoc - D
- [ ] Passo3.0_ResultadoTabela_AvaliaçãoRadoc_Wizard SysRadoc - D
- [ ] Passo3.1_Falha_PDF_AvaliaçãoRadoc_Wizard SysRadoc - D
- [ ] Home_Radoc SysRadoc - D
- [ ] Configurações_TrocarSenha_RemoverConta SysRadoc - D
- [ ] TrocarSenha_Configurações SysRadoc - D
- [ ] RemoverConta_Configurações SysRadoc - D
